# config/packages/nelmio_cors.yaml
nelmio_cors:
    defaults:
        allow_origin: ['*']
        allow_methods: ['GET', 'POST']
        allow_headers: ['Content-Type', 'Authorization']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['Content-Type', 'Authorization']