networks: 
  openrouterappnetwork:
    driver: bridge

secrets:
  db_root_password:
    file: ./db_root_password.txt

services:
  # MariaDB
  db:
    container_name: db-ora
    restart: unless-stopped
    image: mariadb:11.6
    networks:
      - openrouterappnetwork
    ports:
      - "3508:3306"
    volumes:
      - db:/var/lib/mysql
    secrets:
      - db_root_password
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MARIADB_DATABASE: openrouterapp
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # PhpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: pma-ora
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "9311:80"
    secrets:
      - db_root_password
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      UPLOAD_LIMIT: 64M
      PHP_UPLOAD_MAX_FILESIZE: 64M
      PHP_POST_MAX_SIZE: 64M
    networks:
      - openrouterappnetwork

 # PHP
  www:
    user: you
    build: ./docker/php
    container_name: www-ora
    restart: unless-stopped
    networks:
      - openrouterappnetwork
    volumes:
      - ./www:/home/you/ora
    ports:
      - "9310:8800"
    environment:
      SHELL_VERBOSITY: DEBUG
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "php", "-v"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s

#Mkdocs      
  mkdocs:
    container_name: doc-ora
    build: ./docker/mkdocs
    ports:
      - "9312:8000"
    volumes:
      - ./mkdocs:/app
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - openrouterappnetwork

#Symfony
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - "5432"

volumes:
  db:
  database_data:
